name: 'CodeQL'

on:
    schedule:
        - cron: '30 1 * * *'

jobs:
    analyze:
        name: Analyze
        runs-on: ubuntu-latest

        permissions:
            security-events: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@master

            - name: Initialize CodeQL
              uses: github/codeql-action/init@main
              with:
                  languages: typescript

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@main
